---
title: "ESPM 215 - Generalized Additive Models (GAMs)"
author: "Dorothy Chen, Kenzo Esquivel, Kane Russell, and Yvonne Socolar"
date: "2/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Potential datasets
```{r}
ISIT <- read.delim('ISIT.txt') # bioluminescence dataset (Zuur Ch. 3, 17)
RK <- read.delim('RoadKills.txt') # amphibian roadkills dataset (Zuur Ch. 16)
GF <- read.csv('jpe12720-sup-0003-apps2-greenfinch.csv')
GC <- read.csv('jpe12720-sup-0002-apps2-goldcrest.csv')
head(ISIT)
head(RK)
head(GF)
head(GC)
```

## Show model fitting with different values of lambda

```{r}
ISIT$fMonth <- factor(ISIT$Month)
ISIT$fStation <- factor(ISIT$Station)
ISIT$fYear <- factor(ISIT$Year)
ISIT2 <- ISIT[ISIT$fStation != "4" &
              ISIT$fStation != "5" &
              ISIT$fStation != "10" ,]
ISIT2$Depth1000 <- ISIT2$SampleDepth/1000
head(ISIT2)
```

```{r}
gamfit1 <- gam(Sources ~ fStation + s(Depth1000) + fMonth, 
               data = ISIT2)
plot(gamfit1)
gam.check(gamfit1)
summary(gamfit1)
```

```{r}
gamfit2 <- gam(Sources ~ s(fStation, bs = 're') + s(Depth1000) + fMonth, 
               data = ISIT2)
plot(gamfit2)
gam.check(gamfit2)
summary(gamfit2)
```

```{r}
gammfit3 <- gamm(Sources ~ s(Depth1000) + fMonth, 
                 random = list(fStation =~ 1), 
                 data = ISIT2)
plot(gammfit3$gam)
gam.check(gammfit3$gam)
summary(gammfit3$gam)
summary(gammfit3$lme)
```

```{r}
# gammfit4 <- gamm(Sources ~ s(Depth1000) + fMonth, 
#                  random = list(fStation =~ 1), 
#                  data = ISIT2, 
#                  weights = varComb(varIdent(form =~ 1 | fStation), 
#                                    varPower(form =~ Depth1000 | fStation)), 
#                  method = "REML", 
#                  control = lmeControl(niterEM = 5000, msMaxIter = 1000))
```

```{r}
AIC(gamfit1)
AIC(gamfit2)
AIC(gammfit3$lme)
```

```{r}
gamfit1$sp
gamfit1$gcv.ubre
```

```{r}
library(tidyverse)

lambda <- seq(0.0001, 0.002, by = 0.0001)
GCV <- 0

for (i in 1:length(lambda)) {
  gam_fit <- gam(Sources ~ fStation + fMonth + s(Depth1000, sp = lambda[i]), data = ISIT2) 
  GCV[i] <- gam_fit$gcv.ubre
}

table <- data.frame(lambda, GCV)
table

ggplot(data = table) +
  aes(x = lambda, y = GCV) + 
  geom_line()
```

```{r}
plot(gam(Sources ~ fStation + fMonth + s(Depth1000, sp = 0.00011), data = ISIT2))
plot(gam(Sources ~ fStation + fMonth + s(Depth1000, sp = 0.0011), data = ISIT2))
plot(gam(Sources ~ fStation + fMonth + s(Depth1000, sp = 1.1), data = ISIT2))
```


## LOESS Span Sizes

<<<<<<< HEAD


## GAM with single explanatory variable - go through output
=======
>>>>>>> f9076cc1c00a953644cfb91e9e5fb978d52f1fe1



## Create graph similar to Fig. 3.11 (Zuur et al. 2009) of lambda vs GCV, compare with automatic GCV



<<<<<<< HEAD
## Comparison of GLM, GAM, GAMM using AIC, GCV, analysis of deviance, power analysis?
- multiple explanatory variables, interactions?
=======
## different kinds of splines display



## fit GAM and GAMM for paper data (and GLM?)



## different packages



## Explain model summary outputs
>>>>>>> f9076cc1c00a953644cfb91e9e5fb978d52f1fe1



